-- Arachi V2 schema for Postgres (Supabase).
-- The server connects directly with the database owner role, which bypasses
-- RLS. RLS is enabled on every table with no policies, so the Supabase Data
-- API (anon / authenticated keys) can read or write nothing.

CREATE TABLE settings (
  key text PRIMARY KEY,
  value text NOT NULL
);

CREATE TABLE outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel text NOT NULL,
  recipient text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  delivered integer NOT NULL,
  error text,
  provider_id text,
  created_at text NOT NULL
);

CREATE TABLE rfqs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origin text NOT NULL,
  destination text NOT NULL,
  cargo_type text NOT NULL,
  weight_kg double precision NOT NULL,
  volume_m3 double precision NOT NULL DEFAULT 0,
  pallets integer NOT NULL DEFAULT 0,
  transport_type text NOT NULL,
  loading_date text NOT NULL DEFAULT '',
  delivery_date text NOT NULL DEFAULT '',
  currency text NOT NULL,
  offer_deadline text NOT NULL,
  notes text NOT NULL DEFAULT '',
  source text NOT NULL DEFAULT 'chat',
  status text NOT NULL DEFAULT 'open',
  created_at text NOT NULL,
  awarded_offer_id bigint,
  awarded_at text
);

CREATE TABLE carriers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  phone text NOT NULL DEFAULT '',
  whatsapp text NOT NULL DEFAULT '',
  telegram text NOT NULL DEFAULT '',
  category text NOT NULL,
  subcategory text NOT NULL DEFAULT '',
  language text NOT NULL DEFAULT 'az',
  active integer NOT NULL DEFAULT 1,
  created_at text NOT NULL
);
CREATE UNIQUE INDEX carriers_email ON carriers (lower(email)) WHERE email IS NOT NULL;

CREATE TABLE dispatches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rfq_id bigint NOT NULL REFERENCES rfqs (id),
  carrier_id bigint NOT NULL REFERENCES carriers (id),
  channel text NOT NULL,
  status text NOT NULL,
  error text,
  sent_at text NOT NULL,
  viewed_at text,
  reminder_count integer NOT NULL DEFAULT 0,
  last_reminder_at text,
  UNIQUE (rfq_id, carrier_id)
);

CREATE TABLE offers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rfq_id bigint NOT NULL REFERENCES rfqs (id),
  carrier_id bigint NOT NULL REFERENCES carriers (id),
  dispatch_id bigint REFERENCES dispatches (id),
  version integer NOT NULL,
  price double precision NOT NULL,
  currency text NOT NULL,
  transit_days integer NOT NULL,
  valid_until text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  source text NOT NULL,
  created_at text NOT NULL,
  UNIQUE (rfq_id, carrier_id, version)
);
CREATE INDEX offers_carrier ON offers (carrier_id);

ALTER TABLE rfqs ADD CONSTRAINT rfqs_awarded_offer FOREIGN KEY (awarded_offer_id) REFERENCES offers (id);

CREATE TABLE files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_kind text NOT NULL,
  owner_id bigint NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  data bytea NOT NULL,
  created_at text NOT NULL
);
CREATE INDEX files_owner ON files (owner_kind, owner_id);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE carriers ENABLE ROW LEVEL SECURITY;
ALTER TABLE dispatches ENABLE ROW LEVEL SECURITY;
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
