-- User accounts: email + password login, server-side sessions, password
-- reset links. Every RFQ, carrier and outgoing message belongs to one user;
-- dispatches and offers belong to the user through their RFQ.
-- Rows created before accounts existed have no owner (user_id NULL) until
-- the first user registers and takes them over.

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  name text NOT NULL DEFAULT '',
  password_hash text NOT NULL,
  created_at text NOT NULL
);
CREATE UNIQUE INDEX users_email ON users (lower(email));

-- id is the SHA-256 of the cookie token, so a database leak reveals no live session.
CREATE TABLE sessions (
  id text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at text NOT NULL,
  expires_at text NOT NULL
);
CREATE INDEX sessions_user ON sessions (user_id);

CREATE TABLE password_resets (
  id text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at text NOT NULL,
  expires_at text NOT NULL,
  used_at text
);
CREATE INDEX password_resets_user ON password_resets (user_id);

ALTER TABLE rfqs ADD COLUMN user_id bigint REFERENCES users (id);
ALTER TABLE carriers ADD COLUMN user_id bigint REFERENCES users (id);
ALTER TABLE outbox ADD COLUMN user_id bigint REFERENCES users (id);
CREATE INDEX rfqs_user ON rfqs (user_id);
CREATE INDEX outbox_user ON outbox (user_id);

-- A carrier's email is unique per user, not across all users.
DROP INDEX carriers_email;
CREATE UNIQUE INDEX carriers_email ON carriers (user_id, lower(email)) WHERE email IS NOT NULL;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_resets ENABLE ROW LEVEL SECURITY;
