-- Chat history: every user's conversations with the agent. Messages are
-- what the chat shows (text, attachment names, generated files); context is
-- the model's own transcript of the latest turns (JSON, one array per turn),
-- so an old conversation can be continued where it stopped.

CREATE TABLE conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title text NOT NULL,
  context text NOT NULL DEFAULT '[]',
  created_at text NOT NULL,
  updated_at text NOT NULL
);
CREATE INDEX conversations_user ON conversations (user_id, updated_at);

CREATE TABLE conversation_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
  role text NOT NULL,
  text text NOT NULL,
  attachments text NOT NULL DEFAULT '[]',
  downloads text NOT NULL DEFAULT '[]',
  created_at text NOT NULL
);
CREATE INDEX conversation_messages_conversation ON conversation_messages (conversation_id, id);

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_messages ENABLE ROW LEVEL SECURITY;
